name: bar
description: "Title bars"
version: 1.0.1
repository: https://github.com/ArcaneArts/bar
environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  modern_titlebar_buttons: ">=1.1.0 <2.0.0"
  universal_io: ">=2.2.0 <3.0.0"
dev_dependencies:
  flutter_test:
    sdk: flutter