name: bar
description: "Title bars"
version: 1.0.0
repository: https://github.com/ArcaneArts/bar
environment:
  sdk: ^3.7.0

dependency_overrides:
  modern_titlebar_buttons:
    git:
      url: https://github.com/ArcaneArts/modern_titlebar_buttons.git
      ref: updatedshit

dependencies:
  flutter:
    sdk: flutter
  modern_titlebar_buttons: ^1.1.1
  universal_io: ^2.2.2
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter